//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBICINBPaymentStatus
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://thirdparties.sbi.com", ConfigurationName = "SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType")]
    public interface DoubleVerifyMerchantServicePortType
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http://thirdparties.sbi.com/xsd) of message DoubleVerificationRequest does not match the default value (http://thirdparties.sbi.com)
        [System.ServiceModel.OperationContractAttribute(Action = "urn:DoubleVerification", ReplyAction = "urn:DoubleVerificationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        SBICINBPaymentStatus.DoubleVerificationResponse DoubleVerification(SBICINBPaymentStatus.DoubleVerificationRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:DoubleVerification", ReplyAction = "urn:DoubleVerificationResponse")]
        System.Threading.Tasks.Task<SBICINBPaymentStatus.DoubleVerificationResponse> DoubleVerificationAsync(SBICINBPaymentStatus.DoubleVerificationRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://thirdparties.sbi.com/xsd) of message setDoubleVerificationService does not match the default value (http://thirdparties.sbi.com)
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "urn:setDoubleVerificationService")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        void setDoubleVerificationService(SBICINBPaymentStatus.setDoubleVerificationService request);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "urn:setDoubleVerificationService")]
        System.Threading.Tasks.Task setDoubleVerificationServiceAsync(SBICINBPaymentStatus.setDoubleVerificationService request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "DoubleVerification", WrapperNamespace = "http://thirdparties.sbi.com/xsd", IsWrapped = true)]
    public partial class DoubleVerificationRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://thirdparties.sbi.com/xsd", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string strMerchantParm;

        public DoubleVerificationRequest()
        {
        }

        public DoubleVerificationRequest(string strMerchantParm)
        {
            this.strMerchantParm = strMerchantParm;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "DoubleVerificationResponse", WrapperNamespace = "http://thirdparties.sbi.com/xsd", IsWrapped = true)]
    public partial class DoubleVerificationResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://thirdparties.sbi.com/xsd", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string @return;

        public DoubleVerificationResponse()
        {
        }

        public DoubleVerificationResponse(string @return)
        {
            this.@return = @return;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.common.sbi.com/xsd")]
    public partial class BaseService : object, System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "setDoubleVerificationService", WrapperNamespace = "http://thirdparties.sbi.com/xsd", IsWrapped = true)]
    public partial class setDoubleVerificationService
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://thirdparties.sbi.com/xsd", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SBICINBPaymentStatus.BaseService doubleVerificationService;

        public setDoubleVerificationService()
        {
        }

        public setDoubleVerificationService(SBICINBPaymentStatus.BaseService doubleVerificationService)
        {
            this.doubleVerificationService = doubleVerificationService;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoubleVerifyMerchantServicePortTypeChannel : SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoubleVerifyMerchantServicePortTypeClient : System.ServiceModel.ClientBase<SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType>, SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType
    {

        public DoubleVerifyMerchantServicePortTypeClient()
        {
        }

        public DoubleVerifyMerchantServicePortTypeClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public DoubleVerifyMerchantServicePortTypeClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DoubleVerifyMerchantServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DoubleVerifyMerchantServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBICINBPaymentStatus.DoubleVerificationResponse SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType.DoubleVerification(SBICINBPaymentStatus.DoubleVerificationRequest request)
        {
            return base.Channel.DoubleVerification(request);
        }

        public string DoubleVerification(string strMerchantParm)
        {
            SBICINBPaymentStatus.DoubleVerificationRequest inValue = new SBICINBPaymentStatus.DoubleVerificationRequest();
            inValue.strMerchantParm = strMerchantParm;
            SBICINBPaymentStatus.DoubleVerificationResponse retVal = ((SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType)(this)).DoubleVerification(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SBICINBPaymentStatus.DoubleVerificationResponse> SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType.DoubleVerificationAsync(SBICINBPaymentStatus.DoubleVerificationRequest request)
        {
            return base.Channel.DoubleVerificationAsync(request);
        }

        public System.Threading.Tasks.Task<SBICINBPaymentStatus.DoubleVerificationResponse> DoubleVerificationAsync(string strMerchantParm)
        {
            SBICINBPaymentStatus.DoubleVerificationRequest inValue = new SBICINBPaymentStatus.DoubleVerificationRequest();
            inValue.strMerchantParm = strMerchantParm;
            return ((SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType)(this)).DoubleVerificationAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType.setDoubleVerificationService(SBICINBPaymentStatus.setDoubleVerificationService request)
        {
            base.Channel.setDoubleVerificationService(request);
        }

        public void setDoubleVerificationService(SBICINBPaymentStatus.BaseService doubleVerificationService)
        {
            SBICINBPaymentStatus.setDoubleVerificationService inValue = new SBICINBPaymentStatus.setDoubleVerificationService();
            inValue.doubleVerificationService = doubleVerificationService;
            ((SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType)(this)).setDoubleVerificationService(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType.setDoubleVerificationServiceAsync(SBICINBPaymentStatus.setDoubleVerificationService request)
        {
            return base.Channel.setDoubleVerificationServiceAsync(request);
        }

        public System.Threading.Tasks.Task setDoubleVerificationServiceAsync(SBICINBPaymentStatus.BaseService doubleVerificationService)
        {
            SBICINBPaymentStatus.setDoubleVerificationService inValue = new SBICINBPaymentStatus.setDoubleVerificationService();
            inValue.doubleVerificationService = doubleVerificationService;
            return ((SBICINBPaymentStatus.DoubleVerifyMerchantServicePortType)(this)).setDoubleVerificationServiceAsync(inValue);
        }
    }
}
